-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 23:19:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdarchivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdarchivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdarchivo` DEFAULT CHARACTER SET utf8 ;
USE `bdarchivo` ;

-- -----------------------------------------------------
-- Table `bdarchivo`.`tblusuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tblusuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(70) NOT NULL,
  `ndni` VARCHAR(8) NOT NULL,
  `carnet` VARCHAR(15) NOT NULL,
  `contacto` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tblmotivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tblmotivo` (
  `id_motivo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_motivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tblarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tblarea` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tblresolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tblresolucion` (
  `id_resolucion` INT NOT NULL AUTO_INCREMENT,
  `id_motivo` INT NOT NULL,
  `id_area` INT NOT NULL,
  `nresolucion` VARCHAR(5) NOT NULL,
  `nproyecto` VARCHAR(5) NOT NULL,
  `f_emision` DATE NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `est_tbl` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_resolucion`),
  INDEX `fk_resolucion_motivo_idx` (`id_motivo` ASC) ,
  INDEX `fk_resolucion_areap_idx` (`id_area` ASC) ,
  CONSTRAINT `fk_resolucion_motivo`
    FOREIGN KEY (`id_motivo`)
    REFERENCES `bdarchivo`.`tblmotivo` (`id_motivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resolucion_areap`
    FOREIGN KEY (`id_area`)
    REFERENCES `bdarchivo`.`tblarea` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tblinstitucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tblinstitucion` (
  `id_institucion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `nivel` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_institucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tbl_detresolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tbl_detresolucion` (
  `id_detresolucion` INT NOT NULL AUTO_INCREMENT,
  `id_resolucion` INT NOT NULL,
  `id_usuario` INT NULL,
  `id_institucion` INT NULL,
  `f_entrega` DATE NULL,
  `estado` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_detresolucion`),
  INDEX `fk_detresolucion_usuarios_idx` (`id_usuario` ASC) ,
  INDEX `fk_detresolucion_resolucion_idx` (`id_resolucion` ASC) ,
  INDEX `fk_detresolucion_institucion_idx` (`id_institucion` ASC) ,
  CONSTRAINT `fk_detresolucion_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bdarchivo`.`tblusuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detresolucion_resolucion`
    FOREIGN KEY (`id_resolucion`)
    REFERENCES `bdarchivo`.`tblresolucion` (`id_resolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detresolucion_institucion`
    FOREIGN KEY (`id_institucion`)
    REFERENCES `bdarchivo`.`tblinstitucion` (`id_institucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tbladmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tbladmin` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `ndni` VARCHAR(15) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tblpersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tblpersonal` (
  `id_personal` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tblcontrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tblcontrol` (
  `id_control` INT NOT NULL AUTO_INCREMENT,
  `id_personal` INT NOT NULL,
  `id_area` INT NOT NULL,
  `nfolios` VARCHAR(5) NOT NULL,
  `f_entrega` DATE NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_control`),
  INDEX `fk_control_personal_idx` (`id_personal` ASC) ,
  INDEX `fk_control_area_idx` (`id_area` ASC) ,
  CONSTRAINT `fk_control_personal`
    FOREIGN KEY (`id_personal`)
    REFERENCES `bdarchivo`.`tblpersonal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_control_area`
    FOREIGN KEY (`id_area`)
    REFERENCES `bdarchivo`.`tblarea` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdarchivo`.`tbl_detcontrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdarchivo`.`tbl_detcontrol` (
  `id_detcontrol` INT NOT NULL AUTO_INCREMENT,
  `id_control` INT NOT NULL,
  `id_resolucion` INT NOT NULL,
  `f_recepcion` DATE NULL,
  `estado` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_detcontrol`),
  INDEX `fk_detcontrol_resolucion_idx` (`id_resolucion` ASC) ,
  INDEX `fk_detcontrol_control_idx` (`id_control` ASC) ,
  CONSTRAINT `fk_detcontrol_resolucion`
    FOREIGN KEY (`id_resolucion`)
    REFERENCES `bdarchivo`.`tblresolucion` (`id_resolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detcontrol_control`
    FOREIGN KEY (`id_control`)
    REFERENCES `bdarchivo`.`tblcontrol` (`id_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
